site_name: MkDocs Test
site_author: Berkant Şahin

repo_name: berkantsahn/mkdocs-test
repo_url: https://github.com/berkantsahn/mkdocs-test
theme:
  name: material
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Karanlık moda geç
  - media: '(prefers-color-scheme: light)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Aydınlık moda geç
  features:
    - search.suggest
    - search.highlight
    - navigation.sections
    - content.code.copy
  icon:
    repo: fontawesome/brands/git-alt
  language: tr
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/berkantsahn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/berkantsahn
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/berkantsahn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/berkantsahn
  alternate:
  - link: /mkdocs-test/tr/index-tr
    name: tr - Türkçe
  - link: /mkdocs-test/en/index-en
    name: en - English
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
copyright: |
  &copy; 2023 <a href="https://github.com/berkantsahn"  target="_blank" rel="noopener">Berkant Şahin</a>