site_name: MkDocs Test
site_author: Berkant Şahin

repo_name: berkantsahn/mkdocs-test
repo_url: https://github.com/berkantsahn/mkdocs-test
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.sections
    - content.code.copy
  language: tr
nav: 
- mkdocs-test: index.md
- Languages:
  - tr: /
  - en: /en/
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Karanlık moda geç
    primary: teal
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Aydınlık moda geç
      primary: teal
      accent: lime
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/berkantsahn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/berkantsahn
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/berkantsahn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/berkantsahn
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
plugins:
  - search
copyright: |
  &copy; 2023 <a href="https://github.com/berkantsahn"  target="_blank" rel="noopener">Berkant Şahin</a>