name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build TR docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.tr.yml

      - name: Build EN docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.en.yml

      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
